export const themeImages = theme => ({
  loading: `/images/${theme}/loading.gif`,
  blank: `/images/${theme}/icon-prestamos-blank.svg`,
  error: `/images/${theme}/error.svg`,
  checkIlus: `/images/${theme}/check.svg`,
  errorIlus: `/images/${theme}/error.svg`,
  accreditationIlus: `/images/${theme}/transferencias.svg`,
  flags: `/images/flags.png`,
  mobileImage: `/images/mobile-image.png`,
  landingImage: `/images/banner-landing.png`,
  alertsuccess: `/images/alert-check.svg`,
  alerterror: `/images/alert-error.svg`,
  alertinfo: `/images/alert-info.svg`,
  alertwarning: `/images/alert-warning.svg`,
  card: `/images/icon-card.svg`,
  time: `/images/icon-time.svg`,
  iconExecutive: `/images/icon-executive.svg`,
  timelapse: `/images/${theme}/icon-timelapse.svg`,
  logo: `/images/${theme}/logo.svg`,

  //ilustration card
  isoGaliciaIcon: `/images/${theme}/galicia.svg`,
  afipIcon: `/images/${theme}/afip.svg`,
  bellIcon: `/images/${theme}/bell.svg`,
  coordenadasIcon: `/images/${theme}/coordenadas.svg`,
  docsIcon: `/images/${theme}/docs.svg`,
  groupIcon: `/images/${theme}/group.svg`,
  icecreamIcon: `/images/${theme}/icecream.svg`,
  impuestosIcon: `/images/${theme}/impuestos.svg`,
  keysIcon: `/images/${theme}/keys.svg`,
  userIcon: `/images/${theme}/user-icon.svg`,

  //ilustration traking
  trackingDocumentacionError: `/images/tracking-imagenes/icon_prestamos-documentacion-error.svg`,
  trackingDocumentacionEvaluadaOk: `/images/tracking-imagenes/icon_prestamos-documentacion-evaluada-ok.svg`,
  trackingdocumentosOk: `/images/tracking-imagenes/icon_prestamos-documentos-ok.svg`,
  trackingDocumentacionSubida: `/images/tracking-imagenes/icon_prestamos-documentacion-subida.svg`,
  trackingError: `/images/tracking-imagenes/icon_prestamos-error.svg`,
  trackingEscribano: `/images/tracking-imagenes/icon_prestamos-escribano.svg`,
  trackingFelicitaciones: `/images/tracking-imagenes/icon_prestamos-felicitaciones.svg`,
  trackingFirma: `/images/tracking-imagenes/icon_prestamos-firma.svg`,
  trackingnoIniciado: `/images/tracking-imagenes/icon_prestamos-no-iniciado.svg`,
  trackingseguroListo: `/images/tracking-imagenes/icon_prestamos-seguro-listo.svg`,
  trackingseguros: `/images/tracking-imagenes/icon_prestamos-seguros.svg`,
  trackingsinPrestamos: `/images/tracking-imagenes/icon_prestamos-sin-prestamos.svg`,
  trackingTasacion: `/images/tracking-imagenes/icon_prestamos-tasacion.svg`,
  trackingTasacionEspera: `/images/tracking-imagenes/icon_prestamos-tasacion-espera.svg`,

  //Cards providers logo
  amex: `/images/amex.png`,
  amex_: `/images/amex_.png`,
  master: `/images/master.png`,
  master_: `/images/master_.png`,
  visa: `/images/visa.png`,
  visa_: `/images/visa_.png`,

  //Cards icon card
  cardIconAmexBlack: `/images/icon-card-amex-black.svg`,
  cardIconAmexGold: `/images/icon-card-amex-gold.svg`,
  cardIconAmexInternacional: `/images/icon-card-amex-internacional.svg`,
  cardIconAmexPlatinium: `/images/icon-card-amex-platinum.svg`,
  cardIconMasterBlack: `/images/icon-card-master-black.svg`,
  cardIconMasterGold: `/images/icon-card-master-gold.svg`,
  cardIconMasterInter: `/images/icon-card-master-inter.svg`,
  cardIconMasterPlatinium: `/images/icon-card-master-platinum.svg`,
  cardIconVisaBlack: `/images/icon-card-visa-black.svg`,
  cardIconVisaGold: `/images/icon-card-visa-gold.svg`,
  cardIconVisaInter: `/images/icon-card-visa-inter.svg`,
  cardIconVisaPlati: `/images/icon-card-visa-plati.svg`,
});
