export declare type ZIndexApplications = {
    [name: string]: number;
};
export declare type ZIndex = {
    zIndex1: number;
    zIndex2: number;
    zIndex3: number;
    zIndex4: number;
    zIndex5: number;
    zIndex6: number;
    zIndex7: number;
    zIndex8: number;
    zIndex9: number;
    zIndex10: number;
    zIndex11: number;
    zIndex12: number;
    zIndex13: number;
    zIndex14: number;
    zIndex15: number;
    zIndex16: number;
    zIndex17: number;
    zIndex18: number;
    zIndex19: number;
    applications: ZIndexApplications;
};
declare const zIndex: {
    zIndex1: number;
    zIndex2: number;
    zIndex3: number;
    zIndex4: number;
    zIndex5: number;
    zIndex6: number;
    zIndex7: number;
    zIndex8: number;
    zIndex9: number;
    zIndex10: number;
    zIndex11: number;
    zIndex12: number;
    zIndex13: number;
    zIndex14: number;
    zIndex15: number;
    zIndex16: number;
    zIndex17: number;
    zIndex18: number;
    zIndex19: number;
    applications: {
        dropdown: number;
        sticky: number;
        fixed: number;
        offCanvas: number;
        modalBackdrop: number;
        modal: number;
        popover: number;
        tooltip: number;
    };
};
export default zIndex;
